//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzeriaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public int ProductListid { get; set; }
        public string Quantity { get; set; }
        public int Productid { get; set; }
        public Nullable<int> Orderid { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
